FROM certbot/certbot

RUN certbot certonly --webroot --webroot-path=/var/www/certbot --email edoardo.viviani@gmail.com --agree-tos --no-eff-email --force-renewal -d vaccini.vivedo.me -d api.vaccini.vivedo.me -d pgadmin.vaccini.vivedo.me
