version: '3.7'

services:
  nginx-proxy:
    image: nginx:1.19-alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../nginx.conf:/etc/nginx/nginx.conf
    networks:
      - web

networks:
  web:
    external: true