version: '3.7'

services:
  nginx-proxy:
    image: nginx:1.19-alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../nginx.conf:/etc/nginx/nginx.conf
      - letsencrypt:/etc/letsencrypt
      - certbot:/var/www/certbot
    networks:
      - web

  certbot:
    container_name: certbot
    image: certbot/certbot
    networks:
      - web
    volumes:
      - letsencrypt:/etc/letsencrypt
      - certbot:/var/www/certbot
    restart: unless-stopped
    depends_on:
      - nginx-proxy
    #command: sh -c "certbot certonly --webroot --webroot-path=/var/www/certbot --email edoardo.viviani@gmail.com --agree-tos --no-eff-email --staging -d vaccini.vivedo.me -d api.vaccini.vivedo.me -d pgadmin.vaccini.vivedo.me"
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;"


volumes:
  letsencrypt:
  certbot:

networks:
  web:
    external: true